version: '3.6'
services:
  server:
    build: ./docker/server_img
    image: cs523-server-img:latest
    container_name: cs523-server
    networks:
      - cs523
    volumes:
    - ./tor:/var/lib/tor
    - ./:/server
  client:
    build: ./docker/client_img
    image: cs523-client-img:latest
    container_name: cs523-client
    networks:
      - cs523
    volumes:
    - ./:/client
    privileged: true
networks:
  cs523:
    driver: bridge